version: '3.8'

services:
  app-backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=http://localhost:3000
      - JWT_SECRET=supersecretjwt
      - JWT_REFRESH_SECRET=supersecretrefresh
    depends_on:
      - mongo
      - redis

  app-frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - app-backend

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mongo_data:
